### ISSUE TITLE
node V12.14.0   routines:ssl_choose_client_version:unsupported protocol: 这可咋解决？

### ISSUE THREAD

**Issue by MonsterRHD** [kainonly/cmq-node-sdk#2]
write EPROTO 4406975936:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1929:

Node V12.14.0 一直出现这个问题 换回V10.16.2 没啥问题了

![image](https://user-images.githubusercontent.com/22114576/71608457-70879080-2bbc-11ea-984d-4af6c541c032.png)

**Comment by kainonly** [comment]
node运行是增加参数--tls-min-v1.0
